menu:
    Home: /
    编程: /code/
    人丑更要多读书: /read/
    吉他英雄: /guiter/
    About: /about/

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
ga: UA-65933410-1

# Copyright Infomation
startyear: 2012
